# fly.toml app configuration file generated for drift-6dgu9w on 2026-03-22T04:50:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drift-6dgu9w'
primary_region = 'iad'

[build]

[env]
  DRIFT_DATA_DIR = "/data"
  NODE_ENV = "production"

[mounts]
  source = "drift_data"
  destination = "/data"

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 3377
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[checks]
  [checks.health]
    port = 3377
    type = "http"
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/api/health"

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'
