// ── Poetic Forms Database ────────────────────────────────────────────────────
// Comprehensive registry of global poetic forms with structural constraints
// and cultural metadata. Backward-compatible with the original 6-form schema.

export const FORM_CATEGORIES = [
  { key: 'east-asian',      label: 'East & Southeast Asian' },
  { key: 'european',        label: 'European & Western' },
  { key: 'middle-eastern',  label: 'Middle Eastern & Islamic' },
  { key: 'african',         label: 'African Traditions' },
  { key: 'celtic',          label: 'Celtic & British Isles' },
  { key: 'modern',          label: 'Modern & Invented' },
  { key: 'open',            label: 'Open Forms' },
];

export const POETRY_FORMS = {

  // ── East & Southeast Asian ──────────────────────────────────────────────────

  haiku: {
    name: 'Haiku',
    description: '5 — 7 — 5',
    pattern: [5, 7, 5],
    rhymeScheme: null,
    lineCount: 3,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'Three-line Japanese form capturing a moment in nature through a seasonal image and a cutting juxtaposition.',
    history: 'Evolved from the opening verse (hokku) of collaborative linked-verse poetry (renga) in 17th-century Japan. Matsuo Bashō elevated it to a standalone art form; the term "haiku" was coined by Masaoka Shiki in the 19th century.',
    ethos: 'Presence, brevity, seasonal awareness. The haiku seeks to dissolve the boundary between observer and observed.',
    tips: ['Include a kigo (seasonal reference) to ground the moment', 'Use a kireji (cutting word) to create juxtaposition between two images', 'Avoid abstraction — show, don\'t tell'],
    constraints: ['Traditional: requires kigo (seasonal word) and kireji (cutting word)'],
    notablePoets: ['Matsuo Bashō', 'Yosa Buson', 'Kobayashi Issa', 'Masaoka Shiki'],
    exampleTitle: 'The Old Pond (Bashō)',
  },

  tanka: {
    name: 'Tanka',
    description: '5 — 7 — 5 — 7 — 7',
    pattern: [5, 7, 5, 7, 7],
    rhymeScheme: null,
    lineCount: 5,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'Five-line Japanese form with an upper phrase and lower phrase joined by a pivotal third line.',
    history: 'The oldest Japanese poetic form, dating to the 7th century. The Man\'yōshū (Collection of Ten Thousand Leaves, c. 759) contains over 4,500 tanka. It was the dominant court poetry form for a millennium.',
    ethos: 'Emotional depth through structural pivot. The kami-no-ku (upper 5-7-5) sets the scene; the shimo-no-ku (lower 7-7) deepens or redirects it.',
    tips: ['Use line 3 as a pivot (kakekotoba) that connects to both the upper and lower phrases', 'The lower phrase should deepen, not merely continue, the upper phrase', 'Emotional resonance matters more than strict syllable count in English'],
    constraints: ['Pivot line (line 3) should connect both halves'],
    notablePoets: ['Kakinomoto no Hitomaro', 'Ono no Komachi', 'Saigyō', 'Ishikawa Takuboku'],
    exampleTitle: 'Man\'yōshū anthology',
  },

  senryu: {
    name: 'Senryū',
    description: '5 — 7 — 5 · human nature',
    pattern: [5, 7, 5],
    rhymeScheme: null,
    lineCount: 3,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'Same 5-7-5 structure as haiku but focused on human nature, irony, and humor rather than nature.',
    history: 'Named after Karai Senryū (1718–1790), a judge of maekuzuke (verse-capping) contests in Edo. Distinguished from haiku by subject matter: human foibles rather than nature.',
    ethos: 'Wry observation of human nature. Where haiku finds beauty in nature, senryū finds comedy and pathos in people.',
    tips: ['No kigo (seasonal word) required — focus on human situations', 'Humor, irony, or satire are welcome', 'The punchline often lands in the final line'],
    constraints: ['No kigo or kireji required (unlike haiku)'],
    notablePoets: ['Karai Senryū', 'Tsukamoto Kunio'],
    exampleTitle: null,
  },

  katauta: {
    name: 'Katauta',
    description: '5 — 7 — 7 · half-poem',
    pattern: [5, 7, 7],
    rhymeScheme: null,
    lineCount: 3,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'A "half-poem" of three lines, originally designed for call-and-response exchange.',
    history: 'One of the earliest Japanese forms, a katauta is literally a "half-poem" — one side of a poetic dialogue. Two katauta together form a sedoka.',
    ethos: 'Incompleteness as invitation. The form implies a missing partner, a question awaiting its answer.',
    tips: ['Think of it as one half of a conversation', 'The 5-7-7 variant emphasizes the trailing resolution', 'Can be paired with another katauta to form a sedoka'],
    constraints: ['Variant patterns: 5-7-5 or 5-7-7'],
    notablePoets: [],
    exampleTitle: null,
  },

  sedoka: {
    name: 'Sedōka',
    description: '5–7–7–5–7–7 · question & answer',
    pattern: [5, 7, 7, 5, 7, 7],
    rhymeScheme: null,
    lineCount: 6,
    stanzas: [3, 3],
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'Two joined katauta forming a question-and-answer poem in six lines.',
    history: 'An ancient Japanese form composed of two katauta. Found in the Man\'yōshū, often used for dialogues or exchanges between lovers.',
    ethos: 'Dialogue and duality. Each half-poem speaks to the other across a structural divide.',
    tips: ['First stanza poses a question or image; second stanza responds', 'The two halves should feel like distinct voices or perspectives', 'The pivot between stanzas is where the poem turns'],
    constraints: ['Two katauta (5-7-7 + 5-7-7) joined as question and answer'],
    notablePoets: [],
    exampleTitle: null,
  },

  choka: {
    name: 'Chōka',
    description: '5–7 alternating · ends 5–7–7',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'partial',
    summary: 'Long Japanese poem alternating 5- and 7-syllable lines, closing with a 5-7-7 cadence.',
    history: 'The longest traditional Japanese form, used for court ceremonies and public occasions in the Nara period (710–794). Kakinomoto no Hitomaro was its greatest practitioner. Often followed by one or more hanka (envoi tanka).',
    ethos: 'Expansive and ceremonial. Where haiku compresses, chōka unfolds — building through accumulation toward a resonant close.',
    tips: ['Alternate 5-7 syllable lines freely', 'End with 5-7-7 to create a tanka-like cadence', 'Consider adding a hanka (envoi tanka) after the main poem'],
    constraints: ['Alternating 5-7 pattern', 'Must end with 5-7-7', 'Variable length — no fixed line count'],
    notablePoets: ['Kakinomoto no Hitomaro', 'Yamanoue no Okura'],
    exampleTitle: null,
  },

  dodoitsu: {
    name: 'Dodoitsu',
    description: '7–7–7–5 · folk song',
    pattern: [7, 7, 7, 5],
    rhymeScheme: null,
    lineCount: 4,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'Four-line unrhymed Japanese folk song form, typically about love or humor.',
    history: 'Emerged during the Edo period (1603–1868) as a popular song form, often performed by geisha. The 7-7-7-5 pattern (26 syllables) gives it a lilting, musical quality distinct from the more literary tanka.',
    ethos: 'Earthy, musical, and intimate. A form for the voice rather than the page — love, longing, and wit.',
    tips: ['The shorter final line creates natural emphasis — save your strongest image for it', 'Themes of love and humor are traditional', 'Think of it as a song lyric more than a literary poem'],
    constraints: [],
    notablePoets: [],
    exampleTitle: null,
  },

  sijo: {
    name: 'Sijo',
    description: '3 lines · 14–16 syl each · twist in line 3',
    pattern: [15, 15, 15],
    rhymeScheme: null,
    lineCount: 3,
    stanzas: null,
    category: 'east-asian',
    origin: 'Korea',
    validationLevel: 'full',
    summary: 'Korean three-line form with a thematic twist or surprise in the final line.',
    history: 'Originated in the Goryeo period (918–1392) and flourished during the Joseon Dynasty. The name means "current tune" or "song of the times." Both aristocrats and commoners wrote sijo, making it one of Korea\'s most democratic literary forms.',
    ethos: 'Statement, development, twist. Line 1 introduces, line 2 develops, line 3 subverts or resolves with a surprising turn.',
    tips: ['Each line has 14-16 syllables, often divided into hemistichs', 'Line 3 must contain a twist, counter-theme, or unexpected resolution', 'The twist often begins with a surprising image or sound in the first few syllables of line 3'],
    constraints: ['14-16 syllables per line (flexible)', 'Line 3 must contain thematic twist'],
    notablePoets: ['Yun Seondo', 'Hwang Jini', 'Kim Sowol'],
    exampleTitle: null,
  },

  lucBat: {
    name: 'Lục Bát',
    description: '6–8 alternating · interlocking rhyme',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'east-asian',
    origin: 'Vietnam',
    validationLevel: 'partial',
    summary: 'Vietnamese national verse form with alternating 6- and 8-syllable lines linked by interlocking rhyme.',
    history: 'The foundational verse form of Vietnamese literature, used in the national epic Truyện Kiều (The Tale of Kiều) by Nguyễn Du (1820). Predates written Vietnamese literature, originating in oral folk poetry.',
    ethos: 'Flowing, musical, and endlessly extensible. The interlocking rhyme creates a chain that can run for thousands of lines.',
    tips: ['6-syllable line rhymes with the 6th syllable of the following 8-syllable line', 'The 8th syllable of the 8-syllable line rhymes with the 6th syllable of the next 6-syllable line', 'In Vietnamese, tonal rules (bằng/trắc) govern which tones can appear at rhyme positions'],
    constraints: ['Alternating 6-8 syllable lines', 'Interlocking rhyme chain between lines', 'Traditional: Vietnamese tonal rules at rhyme positions'],
    notablePoets: ['Nguyễn Du', 'Hồ Xuân Hương'],
    exampleTitle: 'Truyện Kiều (The Tale of Kiều)',
  },

  pantun: {
    name: 'Pantun',
    description: 'ABAB · shadow + meaning',
    pattern: null,
    rhymeScheme: ['A', 'B', 'A', 'B'],
    lineCount: 4,
    stanzas: null,
    category: 'east-asian',
    origin: 'Malay Archipelago',
    validationLevel: 'full',
    summary: 'Malay quatrain where the first two "shadow" lines create an oblique metaphorical link to the meaning in lines 3-4.',
    history: 'One of the oldest Malay literary forms, dating back centuries in oral tradition. Recognized by UNESCO as Intangible Cultural Heritage. Spread throughout Southeast Asia and influenced the French pantoum.',
    ethos: 'Indirection as art. The pembayang (shadow lines 1-2) never state the theme directly — they create a mood, sound, or image that resonates with the maksud (meaning lines 3-4).',
    tips: ['Lines 1-2 (pembayang/shadow) should create imagery that obliquely mirrors lines 3-4 (maksud/meaning)', 'The connection between shadow and meaning can be sonic, visual, or emotional — not necessarily logical', 'ABAB rhyme links the two halves together'],
    constraints: ['Lines 1-2: pembayang (foreshadowing imagery)', 'Lines 3-4: maksud (actual meaning)', 'Connection between halves is oblique, not direct'],
    notablePoets: [],
    exampleTitle: null,
  },

  tanaga: {
    name: 'Tanaga',
    description: '7–7–7–7 · AABB',
    pattern: [7, 7, 7, 7],
    rhymeScheme: ['A', 'A', 'B', 'B'],
    lineCount: 4,
    stanzas: null,
    category: 'east-asian',
    origin: 'Philippines',
    validationLevel: 'full',
    summary: 'Pre-colonial Filipino quatrain of four 7-syllable lines, often encoding riddles or proverbs.',
    history: 'An indigenous Filipino form predating Spanish colonization (pre-1565). Tanaga were inscribed on bamboo and transmitted orally, often containing riddle-like wisdom, proverbs, and courtship verses.',
    ethos: 'Compact wisdom. Each tanaga is a self-contained jewel of meaning — a riddle, a proverb, or a declaration compressed into 28 syllables.',
    tips: ['Rhyme scheme can be AABB or ABAB — both are traditional', 'Riddle-like or proverbial content is characteristic', 'Every syllable counts — aim for maximum density of meaning'],
    constraints: ['Rhyme scheme: AABB or ABAB (both traditional)'],
    notablePoets: [],
    exampleTitle: null,
  },

  americanCinquain: {
    name: 'American Cinquain',
    description: '2–4–6–8–2',
    pattern: [2, 4, 6, 8, 2],
    rhymeScheme: null,
    lineCount: 5,
    stanzas: null,
    category: 'east-asian',
    origin: 'United States',
    validationLevel: 'full',
    summary: 'Five-line form with a 2-4-6-8-2 syllable pattern, swelling to fullness before snapping shut.',
    history: 'Invented by Adelaide Crapsey (1878–1914), inspired by Japanese forms. Published posthumously in her collection Verse (1915). The form captures a moment of perception in a breath-like arc.',
    ethos: 'Expansion and sudden closure. The syllable count swells outward then collapses — like a wave breaking, or a breath released.',
    tips: ['The final 2-syllable line carries enormous weight — choose those words carefully', 'The 8-syllable line is your fullest moment; the 2-syllable ending should reframe it', 'Imagery of stillness punctuated by action works well with this shape'],
    constraints: [],
    notablePoets: ['Adelaide Crapsey'],
    exampleTitle: 'November Night (Crapsey)',
  },

  // ── European & Western ────────────────────────────────────────────────────

  sonnetPetrarchan: {
    name: 'Petrarchan Sonnet',
    description: 'ABBAABBA + CDECDE · 14 lines',
    pattern: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
    rhymeScheme: ['A','B','B','A','A','B','B','A','C','D','E','C','D','E'],
    lineCount: 14,
    stanzas: [8, 6],
    category: 'european',
    origin: 'Italy',
    validationLevel: 'full',
    summary: 'The original sonnet form: an octave poses a question or tension, and the sestet resolves it across a dramatic volta.',
    history: 'Created by Giacomo da Lentini (13th c.), perfected by Francesco Petrarca (Petrarch) in his Canzoniere (1374). The form spread across Europe, becoming the foundation for all subsequent sonnet traditions.',
    ethos: 'Argument and resolution. The volta at line 9 is the emotional hinge — everything before it builds pressure, everything after releases or redirects.',
    tips: ['The volta (turn) at line 9 is crucial — shift tone, perspective, or argument', 'Octave (lines 1-8) states the problem; sestet (lines 9-14) resolves or complicates it', 'Sestet rhyme can also be CDCDCD — the key constraint is the ABBAABBA octave'],
    constraints: ['Volta between octave and sestet', 'Sestet variants: CDECDE, CDCDCD, CDDCEE'],
    notablePoets: ['Petrarch', 'John Milton', 'Elizabeth Barrett Browning', 'Gerard Manley Hopkins'],
    exampleTitle: 'Sonnet 292 (Petrarch)',
  },

  sonnet: {
    name: 'Shakespearean Sonnet',
    description: 'ABAB CDCD EFEF GG · 14 lines',
    pattern: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
    rhymeScheme: ['A','B','A','B', 'C','D','C','D', 'E','F','E','F', 'G','G'],
    lineCount: 14,
    stanzas: [4, 4, 4, 2],
    category: 'european',
    origin: 'England',
    validationLevel: 'full',
    summary: 'Three quatrains develop a theme through variation, then a closing couplet delivers the turn or resolution.',
    history: 'Adapted from the Italian sonnet by Henry Howard, Earl of Surrey (1540s), and perfected by William Shakespeare in his 154-sonnet sequence (published 1609). The simpler rhyme scheme suited English\'s fewer rhyming words.',
    ethos: 'Development through repetition and variation. Each quatrain approaches the theme from a new angle; the couplet snaps it shut.',
    tips: ['Each quatrain should advance the argument or shift perspective', 'The final couplet often inverts, summarizes, or complicates the preceding 12 lines', 'Iambic pentameter: 10 syllables, da-DUM pattern'],
    constraints: [],
    notablePoets: ['William Shakespeare', 'Edmund Spenser', 'Sir Philip Sidney'],
    exampleTitle: 'Sonnet 18 — Shall I compare thee (Shakespeare)',
  },

  sonnetSpenserian: {
    name: 'Spenserian Sonnet',
    description: 'ABAB BCBC CDCD EE · interlocking',
    pattern: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
    rhymeScheme: ['A','B','A','B','B','C','B','C','C','D','C','D','E','E'],
    lineCount: 14,
    stanzas: [4, 4, 4, 2],
    category: 'european',
    origin: 'England',
    validationLevel: 'full',
    summary: 'A sonnet with interlocking rhyme that chains quatrains together, creating fluid continuity.',
    history: 'Invented by Edmund Spenser for his Amoretti sequence (1595). The interlocking rhyme scheme (ABAB BCBC CDCD EE) bridges the Italian and English traditions, linking stanzas through shared rhymes.',
    ethos: 'Continuity through linkage. Where the Shakespearean sonnet compartmentalizes into distinct quatrains, the Spenserian flows between them.',
    tips: ['The shared rhymes between quatrains (B bridges 1-2, C bridges 2-3, D bridges 3-4) create musical continuity', 'Less room for sharp turns between quatrains — think of a continuous argument', 'The closing couplet (EE) still provides resolution'],
    constraints: ['Interlocking rhyme links adjacent quatrains'],
    notablePoets: ['Edmund Spenser'],
    exampleTitle: 'Amoretti (Spenser)',
  },

  villanelle: {
    name: 'Villanelle',
    description: '19 lines · ABA · 2 refrains',
    pattern: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
    rhymeScheme: ['A','B','A', 'A','B','A', 'A','B','A', 'A','B','A', 'A','B','A', 'A','B','A','A'],
    lineCount: 19,
    stanzas: [3, 3, 3, 3, 3, 4],
    category: 'european',
    origin: 'France',
    validationLevel: 'partial',
    summary: 'Nineteen lines built on two refrains that alternate and finally converge in the closing quatrain.',
    history: 'Derives from Italian villanella (peasant song). Jean Passerat wrote the first strict villanelle in 1606. The form gained modern prominence through Dylan Thomas\'s "Do Not Go Gentle into That Good Night" (1951).',
    ethos: 'Obsessive return. The repeating refrains create a circling, incantatory quality — ideal for themes of grief, longing, or fixation.',
    tips: ['Lines 1 and 3 of the first stanza become the two refrains', 'Refrain 1 (line 1) closes stanzas 2, 4, and the final quatrain', 'Refrain 2 (line 3) closes stanzas 3, 5, and the final quatrain', 'Choose refrains that can shift meaning through changing context'],
    constraints: ['Line 1 repeats as lines 6, 12, 18', 'Line 3 repeats as lines 9, 15, 19', 'Only two rhyme sounds throughout (A and B)'],
    notablePoets: ['Dylan Thomas', 'Elizabeth Bishop', 'Sylvia Plath', 'Theodore Roethke'],
    exampleTitle: 'Do Not Go Gentle into That Good Night (Thomas)',
  },

  sestina: {
    name: 'Sestina',
    description: '39 lines · 6 end-words rotate',
    pattern: null,
    rhymeScheme: null,
    lineCount: 39,
    stanzas: [6, 6, 6, 6, 6, 6, 3],
    category: 'european',
    origin: 'Occitania (Provence)',
    validationLevel: 'partial',
    summary: 'Six stanzas of six lines plus a three-line envoi, with six end-words rotating through a fixed spiral pattern.',
    history: 'Invented by the troubadour Arnaut Daniel (12th century). Dante used it in his Rime Petrose. The mathematical rotation pattern (615243) creates a spiral that has fascinated poets for 800 years.',
    ethos: 'Obsessive repetition with variation. The same six words return in every stanza but in shifting positions, creating a kaleidoscopic effect.',
    tips: ['Choose six end-words that are flexible — words with multiple meanings or grammatical functions', 'Rotation order: if stanza N ends 1-2-3-4-5-6, stanza N+1 ends 6-1-5-2-4-3', 'The envoi (3 lines) uses all 6 words: 2 per line (one mid-line, one at end)'],
    constraints: ['6 end-words rotate in order 615243 across stanzas', 'Envoi uses all 6 end-words in 3 lines', 'No rhyme scheme — the end-word repetition replaces rhyme'],
    notablePoets: ['Arnaut Daniel', 'Dante Alighieri', 'Elizabeth Bishop', 'John Ashbery'],
    exampleTitle: 'A Miracle for Breakfast (Bishop)',
  },

  triolet: {
    name: 'Triolet',
    description: '8 lines · ABaAabAB · refrains',
    pattern: [8, 8, 8, 8, 8, 8, 8, 8],
    rhymeScheme: ['A','B','A','A','A','B','A','B'],
    lineCount: 8,
    stanzas: null,
    category: 'european',
    origin: 'France',
    validationLevel: 'partial',
    summary: 'Eight compact lines where lines 1, 4, and 7 are identical, and lines 2 and 8 are identical.',
    history: 'Medieval French form, first appearing in the 13th century. Revived in English by Robert Bridges and Thomas Hardy. Its extreme repetition (5 of 8 lines are repeats) makes it a study in how context changes meaning.',
    ethos: 'Meaning through recurrence. The same lines, returning in new contexts, reveal new facets — like a gem slowly rotated.',
    tips: ['Lines 1 = 4 = 7 (identical), Lines 2 = 8 (identical) — only 3 unique lines', 'Choose opening lines whose meaning can shift with surrounding context', 'The form works well for light verse, but also for haunting repetition'],
    constraints: ['Lines 1, 4, 7 must be identical', 'Lines 2, 8 must be identical', 'Only two rhyme sounds (A and B)'],
    notablePoets: ['Robert Bridges', 'Thomas Hardy', 'Sandra McPherson'],
    exampleTitle: null,
  },

  pantoum: {
    name: 'Pantoum',
    description: 'Quatrains · lines recycle forward',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'european',
    origin: 'Malay Archipelago / France',
    validationLevel: 'partial',
    summary: 'Interlocking quatrains where lines 2 and 4 of each stanza become lines 1 and 3 of the next.',
    history: 'Adapted from the Malay pantun by French poets in the 19th century (Victor Hugo, Charles Baudelaire). The recycling of lines creates a dream-like, recursive quality distinct from the original pantun form.',
    ethos: 'Recursive memory. Each stanza carries forward echoes of the previous one, creating a layered, trance-like progression.',
    tips: ['Lines 2 and 4 of stanza N become lines 1 and 3 of stanza N+1', 'The final stanza often circles back: its lines 2 and 4 are lines 1 and 3 of the first stanza', 'Write lines that can function differently in their new stanza context'],
    constraints: ['Lines 2 & 4 of each stanza become lines 1 & 3 of the next', 'Final stanza traditionally closes the circle back to stanza 1', 'Variable length — any number of quatrains'],
    notablePoets: ['Victor Hugo', 'Charles Baudelaire', 'John Ashbery', 'Carolyn Kizer'],
    exampleTitle: 'Harmonie du soir (Baudelaire)',
  },

  limerick: {
    name: 'Limerick',
    description: 'AABBA · 8–8–5–5–8',
    pattern: [8, 8, 5, 5, 8],
    rhymeScheme: ['A', 'A', 'B', 'B', 'A'],
    lineCount: 5,
    stanzas: null,
    category: 'european',
    origin: 'Ireland / England',
    validationLevel: 'full',
    summary: 'Five-line comic verse with a bouncing anapestic rhythm and AABBA rhyme scheme.',
    history: 'Popularized by Edward Lear in A Book of Nonsense (1846). The name likely derives from the Irish city of Limerick, possibly from a parlor game refrain "Will you come up to Limerick?"',
    ethos: 'Rhythm as comedy. The anapestic bounce (da-da-DUM) creates inherent levity; the short middle lines set up the punchline.',
    tips: ['Anapestic meter: da-da-DUM da-da-DUM da-da-DUM', 'Lines 3-4 are shorter — use them to build tension for the final line', 'The last line often contains the punchline or twist'],
    constraints: ['Anapestic meter throughout'],
    notablePoets: ['Edward Lear', 'Ogden Nash'],
    exampleTitle: 'A Book of Nonsense (Lear)',
  },

  clerihew: {
    name: 'Clerihew',
    description: 'AABB · 4 lines · biographical wit',
    pattern: null,
    rhymeScheme: ['A', 'A', 'B', 'B'],
    lineCount: 4,
    stanzas: null,
    category: 'european',
    origin: 'England',
    validationLevel: 'partial',
    summary: 'Four-line comic biographical verse where the first line is a person\'s name.',
    history: 'Invented by Edmund Clerihew Bentley as a schoolboy (c. 1890). His first clerihew was about Humphry Davy. Published in Biography for Beginners (1905) and Baseless Biography (1939).',
    ethos: 'Deflation through absurdity. The form takes a famous name and attaches an absurd, irreverent observation in rhyming couplets.',
    tips: ['First line MUST be a person\'s name (real or fictional)', 'Deliberately irregular meter — awkwardness is part of the charm', 'The humor comes from the gap between the person\'s stature and the trivial observation'],
    constraints: ['Line 1 must be a proper name', 'Irregular meter is intentional'],
    notablePoets: ['Edmund Clerihew Bentley', 'W. H. Auden'],
    exampleTitle: 'Sir Humphry Davy (Bentley)',
  },

  ballad: {
    name: 'Ballad',
    description: 'ABCB · 8–6–8–6 · storytelling',
    pattern: [8, 6, 8, 6],
    rhymeScheme: ['A', 'B', 'C', 'B'],
    lineCount: 4,
    stanzas: null,
    category: 'european',
    origin: 'British Isles',
    validationLevel: 'full',
    summary: 'Narrative quatrain in common meter — the storytelling workhorse of English verse.',
    history: 'Rooted in medieval oral tradition, ballads were sung narratives passed down through generations. The Child Ballads (305 traditional ballads collected by Francis James Child, 1857-1898) preserve the oldest English-language examples.',
    ethos: 'Story in song. The alternating tetrameter/trimeter (8-6-8-6) creates a rocking, musical rhythm suited to narrative — tales of love, betrayal, adventure, and the supernatural.',
    tips: ['Alternating iambic tetrameter (8) and trimeter (6) = common meter / hymn meter', 'Focus on narrative: action, dialogue, dramatic scenes', 'Repetition and refrains are traditional ballad devices'],
    constraints: ['Also known as common meter or hymn meter'],
    notablePoets: ['Anonymous (traditional)', 'Samuel Taylor Coleridge', 'John Keats', 'Oscar Wilde'],
    exampleTitle: 'The Rime of the Ancient Mariner (Coleridge)',
  },

  rondeau: {
    name: 'Rondeau',
    description: '15 lines · 2 rhymes · rentrement refrain',
    pattern: [8, 8, 8, 8, 8, 8, 8, 8, 4, 8, 8, 8, 8, 8, 4],
    rhymeScheme: ['A','A','B','B','A', 'A','A','B','R', 'A','A','B','B','A','R'],
    lineCount: 15,
    stanzas: [5, 4, 6],
    category: 'european',
    origin: 'France',
    validationLevel: 'partial',
    summary: 'Fifteen lines using only two rhyme sounds, with a rentrement (short refrain drawn from the opening phrase) closing stanzas 2 and 3.',
    history: 'Flourished in 15th-century France with Charles d\'Orléans and François Villon. The rentrement — a partial repetition of the opening line — distinguishes it from other French fixed forms.',
    ethos: 'Musical return. The two-rhyme constraint and recurring rentrement create a song-like quality of departure and return.',
    tips: ['The rentrement (refrain) uses only the first phrase of line 1 — not the full line', 'Only two rhyme sounds (A and B) throughout all 15 lines', 'The rentrement doesn\'t count toward the rhyme scheme — it stands apart'],
    constraints: ['Rentrement = opening phrase of line 1, repeated as short refrain', 'Only 2 rhyme sounds throughout', 'Rentrement closes stanzas 2 and 3'],
    notablePoets: ['Charles d\'Orléans', 'François Villon', 'John McCrae'],
    exampleTitle: 'In Flanders Fields (McCrae)',
  },

  terzaRima: {
    name: 'Terza Rima',
    description: 'ABA BCB CDC · interlocking tercets',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'european',
    origin: 'Italy',
    validationLevel: 'partial',
    summary: 'Interlocking tercets where each middle rhyme becomes the outer rhyme of the next stanza, creating an unbroken chain.',
    history: 'Invented by Dante Alighieri for the Divine Comedy (1308–1320). The interlocking pattern (ABA BCB CDC) mirrors the poem\'s theological structure of threes (Trinity, three canticles, three-line stanzas). Shelley, Byron, and Frost later adopted it in English.',
    ethos: 'Forward propulsion through linkage. Each stanza reaches into the next through its unresolved middle rhyme — the form embodies continuous journey.',
    tips: ['The middle line of each tercet provides the rhyme for the next stanza\'s outer lines', 'Traditionally ends with a single line or couplet that resolves the final middle rhyme', 'Iambic pentameter (10 syllables) is traditional but not required in English'],
    constraints: ['ABA BCB CDC... interlocking chain', 'Traditionally iambic pentameter', 'Ends with a resolving line or couplet'],
    notablePoets: ['Dante Alighieri', 'Percy Bysshe Shelley', 'Robert Frost', 'Derek Walcott'],
    exampleTitle: 'The Divine Comedy (Dante)',
  },

  heroicCouplet: {
    name: 'Heroic Couplet',
    description: 'AA BB CC · iambic pentameter pairs',
    pattern: null,
    rhymeScheme: 'couplet',
    lineCount: null,
    stanzas: null,
    category: 'european',
    origin: 'England',
    validationLevel: 'full',
    summary: 'Rhyming pairs of iambic pentameter lines — the neoclassical workhorse of English verse.',
    history: 'Chaucer used it in The Canterbury Tales (1390s). Perfected by John Dryden and Alexander Pope in the 17th-18th centuries as the dominant form for satire, philosophy, and narrative.',
    ethos: 'Epigrammatic precision. Each couplet is a self-contained unit of thought — balanced, polished, and often witty.',
    tips: ['Each couplet should express a complete thought', 'Closed couplets (sense complete at line end) are traditional; enjambed couplets are modern', 'The form rewards antithesis: set up in line 1, resolve/invert in line 2'],
    constraints: ['Iambic pentameter (10 syllables per line)', 'Each couplet traditionally a closed unit of sense'],
    notablePoets: ['Geoffrey Chaucer', 'Alexander Pope', 'John Dryden'],
    exampleTitle: 'The Rape of the Lock (Pope)',
  },

  blankVerse: {
    name: 'Blank Verse',
    description: 'Unrhymed · iambic pentameter',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'european',
    origin: 'England',
    validationLevel: 'partial',
    summary: 'Unrhymed iambic pentameter — the closest English verse comes to natural speech while maintaining rhythmic structure.',
    history: 'Introduced to English by Henry Howard, Earl of Surrey (1540s). Shakespeare used it for his plays, Milton for Paradise Lost (1667). It became the dominant form for English dramatic and epic verse.',
    ethos: 'The rhythm of thought itself. Without rhyme to create closure, blank verse flows like speech — but the underlying pentameter gives it gravity and shape.',
    tips: ['10 syllables per line, iambic (da-DUM) pattern', 'Enjambment (running sentences across line breaks) is essential to avoid monotony', 'Vary the caesura (mid-line pause) position to create rhythmic interest'],
    constraints: ['Iambic pentameter (10 syllables per line)', 'No rhyme', 'Variable length'],
    notablePoets: ['William Shakespeare', 'John Milton', 'William Wordsworth', 'Robert Frost'],
    exampleTitle: 'Paradise Lost (Milton)',
  },

  ballade: {
    name: 'Ballade',
    description: '3 octaves + envoi · ABABBCBC · refrain',
    pattern: [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
    rhymeScheme: ['A','B','A','B','B','C','B','C', 'A','B','A','B','B','C','B','C', 'A','B','A','B','B','C','B','C', 'B','C','B','C'],
    lineCount: 28,
    stanzas: [8, 8, 8, 4],
    category: 'european',
    origin: 'France',
    validationLevel: 'partial',
    summary: 'Three eight-line stanzas plus a four-line envoi, all sharing the same rhyme sounds, with a refrain closing every stanza.',
    history: 'Mastered by François Villon in the 15th century. Not to be confused with the ballad — the ballade is a strict French fixed form. Villon\'s "Ballade des pendus" and "Ballade des dames du temps jadis" are definitive.',
    ethos: 'Formal grandeur with emotional intensity. The repeating refrain gains weight with each return, and the envoi (often addressed to a prince or patron) delivers the final statement.',
    tips: ['The refrain (last line of each stanza and the envoi) must be identical', 'Only 3 rhyme sounds (A, B, C) across 28 lines — choose versatile rhymes', 'The envoi (4 lines) traditionally begins with "Prince" or an address to the patron'],
    constraints: ['Same refrain closes every stanza and the envoi', 'Only 3 rhyme sounds throughout', 'Envoi traditionally addresses a prince/patron'],
    notablePoets: ['François Villon', 'Geoffrey Chaucer', 'Algernon Charles Swinburne'],
    exampleTitle: 'Ballade des dames du temps jadis (Villon)',
  },

  kyrielle: {
    name: 'Kyrielle',
    description: 'Quatrains · refrain last line · prayer form',
    pattern: [8, 8, 8, 8],
    rhymeScheme: ['A', 'A', 'B', 'B'],
    lineCount: null,
    stanzas: null,
    category: 'european',
    origin: 'France',
    validationLevel: 'partial',
    summary: 'Repeating quatrains where the last line of each stanza is the same refrain — a prayer-like litany in verse.',
    history: 'Named after the Kyrie eleison ("Lord, have mercy") of Christian liturgy. The form\'s repetitive refrain structure mirrors the call-and-response pattern of medieval prayer and litany.',
    ethos: 'Devotional repetition. Like a prayer, the kyrielle builds meaning through the accumulation of stanzas that all arrive at the same refrain — each time with deeper resonance.',
    tips: ['Each stanza ends with the same refrain line', 'Rhyme schemes vary: AABB, ABAB, ABCB are all used', '8 syllables per line is traditional', 'The refrain should gain depth with each repetition'],
    constraints: ['Last line of every stanza is identical (refrain)', 'Variable number of stanzas', 'Rhyme scheme varies by tradition'],
    notablePoets: ['Thomas Campion'],
    exampleTitle: null,
  },

  // ── Middle Eastern & Islamic ──────────────────────────────────────────────

  ghazal: {
    name: 'Ghazal',
    description: 'Couplets · AA BA CA DA · radif + qafiya',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'middle-eastern',
    origin: 'Arabic / Persian / Urdu',
    validationLevel: 'partial',
    summary: 'A series of autonomous couplets united by a strict rhyme-and-refrain pattern, each couplet a self-contained poem.',
    history: 'Originated in 7th-century Arabic poetry, flourished in Persian (Hafiz, Rumi, 13th-14th c.) and Urdu (Ghalib, 19th c.). The matla (opening couplet) establishes the pattern; the maqta (final couplet) contains the poet\'s takhallus (pen name). Agha Shahid Ali championed the form in English.',
    ethos: 'Unity through pattern, autonomy within each couplet. The ghazal is a necklace of jewels — each sher (couplet) is complete in itself, yet bound to the others by the rhyme-refrain chain.',
    tips: ['Matla (first couplet): both lines end with the radif (refrain) preceded by the qafiya (rhyme)', 'Subsequent couplets: only the second line carries the qafiya + radif', 'Each couplet should be self-contained — thematic unity is NOT required between couplets', 'Maqta (final couplet): include your name or pen name (takhallus)'],
    constraints: ['Matla: both lines rhyme (AA)', 'Subsequent couplets: second line rhymes (BA, CA, DA...)', 'Qafiya (rhyme word) + radif (refrain phrase) at each rhyming line end', 'Maqta (final couplet) includes poet\'s takhallus (pen name)', 'Each couplet is thematically autonomous', '5-15 couplets typical'],
    notablePoets: ['Hafiz', 'Rumi', 'Mirza Ghalib', 'Agha Shahid Ali'],
    exampleTitle: 'Even the Rain (Agha Shahid Ali)',
  },

  qasida: {
    name: 'Qasida',
    description: 'Monorhyme · AA AA AA · panegyric ode',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'middle-eastern',
    origin: 'Pre-Islamic Arabia',
    validationLevel: 'partial',
    summary: 'Long monorhyme ode with a tripartite structure: love prelude, desert journey, and praise of the patron.',
    history: 'The oldest Arabic poetic form, predating Islam. The Mu\'allaqat ("Suspended Odes") are the most celebrated pre-Islamic qasidas. Al-Mutanabbi (10th c.) and Imru\' al-Qais are among its greatest practitioners. Can reach 100+ couplets.',
    ethos: 'Ceremonial grandeur and rhetorical power. The tripartite structure (nasib → rahil → madih) enacts a journey from personal longing through hardship to public praise.',
    tips: ['Nasib (opening): love prelude, often at an abandoned campsite', 'Rahil (middle): journey through the desert, descriptions of mount/landscape', 'Madih/Fakhr (closing): praise of patron or tribal boast', 'Single rhyme throughout — choose a versatile rhyme sound'],
    constraints: ['Monorhyme: every line (or both hemistichs of the first line, then every second hemistich) shares one rhyme', 'Tripartite: nasib (love prelude), rahil (journey), madih (panegyric)', 'Can extend to 100+ lines'],
    notablePoets: ['Imru\' al-Qais', 'Al-Mutanabbi', 'Al-Khansa'],
    exampleTitle: 'Mu\'allaqat (The Suspended Odes)',
  },

  rubaiyat: {
    name: 'Rubáiyát',
    description: 'AABA · philosophical quatrains',
    pattern: null,
    rhymeScheme: ['A', 'A', 'B', 'A'],
    lineCount: 4,
    stanzas: null,
    category: 'middle-eastern',
    origin: 'Persia',
    validationLevel: 'full',
    summary: 'Philosophical quatrain with AABA rhyme — the unrhymed third line creates a breath before the closing return.',
    history: 'The rubáʿí (plural rubáiyát) was perfected by Omar Khayyám (11th c.) and immortalized in English by Edward FitzGerald\'s free translation (1859). Each quatrain stands alone as a meditation on transience, wine, fate, or wonder.',
    ethos: 'Philosophical compression. Each quatrain is a complete thought — often a meditation on mortality, pleasure, or the unknowable. The unrhymed third line creates a moment of suspense before the return.',
    tips: ['AABA: the unrhymed 3rd line creates tension resolved by the 4th', 'Each quatrain should be self-contained', 'Themes of impermanence, wine, love, and cosmic mystery are traditional'],
    constraints: ['Each quatrain stands alone as a complete poem'],
    notablePoets: ['Omar Khayyám', 'Edward FitzGerald'],
    exampleTitle: 'Rubáiyát of Omar Khayyám (FitzGerald trans.)',
  },

  masnavi: {
    name: 'Masnavi',
    description: 'AA BB CC · epic narrative couplets',
    pattern: null,
    rhymeScheme: 'couplet',
    lineCount: null,
    stanzas: null,
    category: 'middle-eastern',
    origin: 'Persia',
    validationLevel: 'full',
    summary: 'Epic rhyming couplets for sustained narrative — each couplet carries its own rhyme, enabling endless extension.',
    history: 'The great vehicle for Persian epic and didactic poetry. Rumi\'s Masnavi-ye-Ma\'navi (26,000 couplets) is the masterwork. Ferdowsi\'s Shahnameh (50,000+ couplets) uses the same form for heroic epic. Each couplet rhymes independently (AA BB CC).',
    ethos: 'Narrative momentum. Because each couplet supplies its own rhyme (unlike the monorhyme ghazal or qasida), the masnavi can sustain epic-length narratives without rhyme fatigue.',
    tips: ['Each couplet has its own rhyme — no need to maintain rhyme across couplets', 'The form is designed for long narrative: stories, parables, philosophical argument', 'Rumi embedded stories within stories — nesting is traditional'],
    constraints: ['Each couplet independently rhymed (AA BB CC...)', 'Designed for sustained length — no upper limit'],
    notablePoets: ['Rumi', 'Ferdowsi', 'Nizami', 'Attar'],
    exampleTitle: 'Masnavi-ye-Ma\'navi (Rumi)',
  },

  interlockingRubaiyat: {
    name: 'Interlocking Rubáiyát',
    description: 'AABA → BBCB → CCDC · chain',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'middle-eastern',
    origin: 'Persia',
    validationLevel: 'partial',
    summary: 'Chain of rubáiyát where the unrhymed third line of each quatrain provides the rhyme sound for the next.',
    history: 'A variant of the rubáiyát form where quatrains are linked: the unrhymed B line of AABA becomes the rhyme sound of the next stanza (BBCB), and so on, creating a chain. Robert Frost used this structure in "Stopping by Woods on a Snowy Evening."',
    ethos: 'Forward momentum through linkage. What the standard rubáiyát treats as a pause (the unrhymed 3rd line), the interlocking variant transforms into a bridge to the next stanza.',
    tips: ['AABA → BBCB → CCDC: the unrhymed line becomes the next stanza\'s rhyme', 'The final stanza can close the circle by rhyming back to the first stanza\'s sound', 'Frost\'s "Stopping by Woods" resolves by making the final stanza DDDD (all rhyme)'],
    constraints: ['3rd line of each quatrain seeds the rhyme of the next', 'Chain can be circular (final stanza links back to first)', 'Variable number of quatrains'],
    notablePoets: ['Omar Khayyám', 'Robert Frost'],
    exampleTitle: 'Stopping by Woods on a Snowy Evening (Frost)',
  },

  // ── African Traditions ────────────────────────────────────────────────────

  izibongo: {
    name: 'Praise Poem (Izibongo)',
    description: 'Zulu/Xhosa · praise names · oral performance',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'african',
    origin: 'Zulu / Xhosa (Southern Africa)',
    validationLevel: 'none',
    summary: 'Oral praise poetry performed by an imbongi (praise poet), building identity through accumulated epithets and praise names.',
    history: 'Central to Zulu and Xhosa culture for centuries. The imbongi (praise poet) holds a public role — praising chiefs, warriors, and ancestors at ceremonies. Izithakazelo (clan praise names) are recited to affirm identity and lineage. The tradition continues in modern South African political and cultural life.',
    ethos: 'Accumulation and amplification. The praise poem builds through layered epithets, metaphors, and historical references — each line adding to the subject\'s stature.',
    tips: ['Build through accumulation of epithets and praise names', 'Use parallelism and repetition for rhythmic momentum', 'Address the subject directly — the form is performative', 'Draw on metaphors of nature, strength, and ancestry'],
    constraints: ['Oral performance tradition — meant to be spoken aloud', 'No fixed metrical or rhyme constraints', 'Parallelism and repetition are structural devices'],
    notablePoets: ['Mazisi Kunene', 'Traditional imbongi'],
    exampleTitle: null,
  },

  oriki: {
    name: 'Oriki',
    description: 'Yoruba · praise epithets · chanted',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'african',
    origin: 'Yoruba (West Africa)',
    validationLevel: 'none',
    summary: 'Yoruba praise poetry composed of chanted epithets and attributes for a person, deity, place, or lineage.',
    history: 'A foundational Yoruba oral form, oriki are praise-names and attribute-chains recited for individuals, families, towns, and orisha (deities). Traditionally performed by women at naming ceremonies, festivals, and funerals. The form is accumulative — new lines can always be added.',
    ethos: 'Naming as creation. To speak the oriki is to call forth the essence of the subject — each epithet reveals another facet of their being.',
    tips: ['Build through epithets: "Owner of...", "One who...", "Child of..."', 'Each line can stand alone as a complete praise-attribute', 'The form is open-ended — oriki grow over a lifetime', 'Rhythmic chanting and tonal patterns are central in Yoruba performance'],
    constraints: ['Accumulative structure — no fixed length', 'Epithets and attribute-chains are the building blocks', 'Oral/chanted performance tradition'],
    notablePoets: ['Traditional Yoruba poets'],
    exampleTitle: null,
  },

  gabay: {
    name: 'Gabay',
    description: 'Somali · alliterative · 15 syl · serious',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'african',
    origin: 'Somalia',
    validationLevel: 'partial',
    summary: 'The most prestigious Somali form: long-lined, serious, and bound by mandatory alliteration throughout the entire poem.',
    history: 'The gabay is the highest form in Somali poetry\'s genre hierarchy. Somali poetry is entirely oral (no written tradition until 1972) and governed by quantitative meter (miisaan) and mandatory alliteration (xarafraac). The gabay addresses serious themes: politics, philosophy, clan disputes. Sayyid Mohamed Abdullah Hassan ("Mad Mullah") used gabay as political weapon against colonial powers.',
    ethos: 'Gravitas and intellectual weight. The gabay demands sustained alliteration on a single letter throughout — a feat of verbal skill that marks the poet as a master.',
    tips: ['Choose one alliterative letter (xarafraac) and maintain it in every line', 'Lines are long: approximately 14-16 syllables or 20-21 vowel mora', 'Themes should be weighty: philosophy, politics, justice, clan honor', 'In Somali tradition, the alliterative sound must appear in each hemistich'],
    constraints: ['Mandatory alliteration (xarafraac): single letter throughout entire poem', 'Quantitative meter (miisaan) based on vowel length', 'Approximately 14-16 syllables per line', 'Serious/philosophical subject matter expected'],
    notablePoets: ['Sayyid Mohamed Abdullah Hassan', 'Hadraawi'],
    exampleTitle: null,
  },

  geeraar: {
    name: 'Geeraar',
    description: 'Somali · 7 syl · alliterative · shorter',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'african',
    origin: 'Somalia',
    validationLevel: 'partial',
    summary: 'Shorter Somali form with 7-syllable lines and mandatory alliteration, traditionally for themes of war and pastoral life.',
    history: 'The geeraar occupies a middle position in Somali poetry\'s hierarchy — lighter than the gabay but still respected. Traditionally associated with warfare, horses, and pastoral life. Like all Somali poetry, it requires mandatory alliteration (xarafraac) throughout.',
    ethos: 'Swift and martial. The shorter line (7 syllables vs. gabay\'s 15) creates a faster, more urgent rhythm suited to themes of action and movement.',
    tips: ['Approximately 7 syllables per line — much shorter than gabay', 'Maintain single-letter alliteration throughout', 'Traditional themes: warfare, horses, pastoral life, love'],
    constraints: ['Mandatory alliteration (xarafraac)', 'Approximately 7 syllables per line', 'Lighter register than gabay'],
    notablePoets: [],
    exampleTitle: null,
  },

  buraanbur: {
    name: 'Buraanbur',
    description: 'Somali women\'s · 10 syl · ceremonial',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'african',
    origin: 'Somalia',
    validationLevel: 'partial',
    summary: 'Somali women\'s poetry performed at weddings, births, and celebrations — rhythmic, alliterative, and deeply personal.',
    history: 'The buraanbur is the domain of Somali women poets, performed at weddings, births, and communal celebrations. Like other Somali forms, it requires mandatory alliteration, but its register is personal and emotional rather than political.',
    ethos: 'Celebration and intimacy. The buraanbur brings the power of Somali poetic tradition into the domestic and ceremonial sphere — joy, grief, love, and community.',
    tips: ['Approximately 10 syllables per line', 'Maintain single-letter alliteration throughout', 'Themes: love, celebration, family, women\'s experience', 'Meant to be performed with rhythm and movement'],
    constraints: ['Mandatory alliteration (xarafraac)', 'Approximately 10 syllables per line', 'Women\'s performance tradition'],
    notablePoets: [],
    exampleTitle: null,
  },

  belwo: {
    name: 'Belwo',
    description: 'Modern Somali · short romantic',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'african',
    origin: 'Somalia',
    validationLevel: 'none',
    summary: 'Modern short-form Somali love poetry, alliterative and romantic, born in the 1920s.',
    history: 'Emerged in the 1920s as a modern "miniature" Somali form, pioneered by Abdi Deeqsi. The belwo broke with tradition by being short and focused on romantic love. Despite its brevity, it maintains the Somali requirement of alliteration.',
    ethos: 'Romantic compression. The belwo distills the Somali alliterative tradition into its most intimate and personal expression.',
    tips: ['Keep it short — this is a miniature form', 'Alliteration is still expected', 'Focus on romantic love and personal emotion'],
    constraints: ['Short form — typically just a few lines', 'Alliterative tradition maintained'],
    notablePoets: ['Abdi Deeqsi'],
    exampleTitle: null,
  },

  elegy: {
    name: 'Elegy',
    description: 'Lament · solemn · free structure',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'african',
    origin: 'Universal (cross-cultural)',
    validationLevel: 'none',
    summary: 'A poem of mourning and meditation on death — one of poetry\'s most universal modes.',
    history: 'The elegy spans virtually all cultures and periods. In English, the tradition runs from Anglo-Saxon laments through Milton\'s "Lycidas" (1637), Gray\'s "Elegy Written in a Country Churchyard" (1751), Whitman\'s Lincoln elegies, to modern examples by Auden, Heaney, and others.',
    ethos: 'Grief transformed through language. The elegy moves from lament to consolation (or refuses consolation), making private grief public and shared.',
    tips: ['Traditional movement: from grief → praise of the dead → consolation', 'Modern elegies often resist or complicate consolation', 'The form is open — what makes it an elegy is tone and occasion, not structure'],
    constraints: ['No fixed structural constraints', 'Defined by occasion (death/loss) and tone (solemn/meditative)'],
    notablePoets: ['John Milton', 'Thomas Gray', 'Walt Whitman', 'W. H. Auden', 'Seamus Heaney'],
    exampleTitle: 'Elegy Written in a Country Churchyard (Gray)',
  },

  negritude: {
    name: 'Négritude Verse',
    description: 'Francophone African · rhythmic · anticolonial',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'african',
    origin: 'Francophone Africa / Caribbean',
    validationLevel: 'none',
    summary: 'Rhythmic, somatic free verse reclaiming African identity — a literary movement as much as a form.',
    history: 'Founded in 1930s Paris by Aimé Césaire (Martinique), Léopold Sédar Senghor (Senegal), and Léon-Gontran Damas (French Guiana). Négritude reclaimed Black African cultural identity against colonial assimilation. Senghor\'s poetry in particular draws on African oral rhythms, natural imagery, and embodied experience.',
    ethos: 'Rhythm as resistance. Négritude verse reclaims the body, the land, and African oral tradition as sources of poetic power — against the colonial reduction of African culture.',
    tips: ['Draw on natural imagery: earth, rivers, trees, animals', 'Use rhythm and repetition drawn from oral traditions', 'The body and sensory experience are central — "somatic" poetry', 'Themes: identity, ancestry, resistance, beauty of African culture'],
    constraints: ['Free-form but highly rhythmic and musical', 'Rooted in African oral traditions and natural imagery'],
    notablePoets: ['Aimé Césaire', 'Léopold Sédar Senghor', 'Léon-Gontran Damas'],
    exampleTitle: 'Cahier d\'un retour au pays natal (Césaire)',
  },

  // ── Celtic & British Isles ────────────────────────────────────────────────

  // ── Modern & Invented ─────────────────────────────────────────────────────

  // ── Open Forms ────────────────────────────────────────────────────────────

};
