// ── Poetic Forms Database ────────────────────────────────────────────────────
// Comprehensive registry of global poetic forms with structural constraints
// and cultural metadata. Backward-compatible with the original 6-form schema.

export const FORM_CATEGORIES = [
  { key: 'east-asian',      label: 'East & Southeast Asian' },
  { key: 'european',        label: 'European & Western' },
  { key: 'middle-eastern',  label: 'Middle Eastern & Islamic' },
  { key: 'african',         label: 'African Traditions' },
  { key: 'celtic',          label: 'Celtic & British Isles' },
  { key: 'modern',          label: 'Modern & Invented' },
  { key: 'open',            label: 'Open Forms' },
];

export const POETRY_FORMS = {

  // ── East & Southeast Asian ──────────────────────────────────────────────────

  haiku: {
    name: 'Haiku',
    description: '5 — 7 — 5',
    pattern: [5, 7, 5],
    rhymeScheme: null,
    lineCount: 3,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'Three-line Japanese form capturing a moment in nature through a seasonal image and a cutting juxtaposition.',
    history: 'Evolved from the opening verse (hokku) of collaborative linked-verse poetry (renga) in 17th-century Japan. Matsuo Bashō elevated it to a standalone art form; the term "haiku" was coined by Masaoka Shiki in the 19th century.',
    ethos: 'Presence, brevity, seasonal awareness. The haiku seeks to dissolve the boundary between observer and observed.',
    tips: ['Include a kigo (seasonal reference) to ground the moment', 'Use a kireji (cutting word) to create juxtaposition between two images', 'Avoid abstraction — show, don\'t tell'],
    constraints: ['Traditional: requires kigo (seasonal word) and kireji (cutting word)'],
    notablePoets: ['Matsuo Bashō', 'Yosa Buson', 'Kobayashi Issa', 'Masaoka Shiki'],
    exampleTitle: 'The Old Pond (Bashō)',
  },

  tanka: {
    name: 'Tanka',
    description: '5 — 7 — 5 — 7 — 7',
    pattern: [5, 7, 5, 7, 7],
    rhymeScheme: null,
    lineCount: 5,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'Five-line Japanese form with an upper phrase and lower phrase joined by a pivotal third line.',
    history: 'The oldest Japanese poetic form, dating to the 7th century. The Man\'yōshū (Collection of Ten Thousand Leaves, c. 759) contains over 4,500 tanka. It was the dominant court poetry form for a millennium.',
    ethos: 'Emotional depth through structural pivot. The kami-no-ku (upper 5-7-5) sets the scene; the shimo-no-ku (lower 7-7) deepens or redirects it.',
    tips: ['Use line 3 as a pivot (kakekotoba) that connects to both the upper and lower phrases', 'The lower phrase should deepen, not merely continue, the upper phrase', 'Emotional resonance matters more than strict syllable count in English'],
    constraints: ['Pivot line (line 3) should connect both halves'],
    notablePoets: ['Kakinomoto no Hitomaro', 'Ono no Komachi', 'Saigyō', 'Ishikawa Takuboku'],
    exampleTitle: 'Man\'yōshū anthology',
  },

  senryu: {
    name: 'Senryū',
    description: '5 — 7 — 5 · human nature',
    pattern: [5, 7, 5],
    rhymeScheme: null,
    lineCount: 3,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'Same 5-7-5 structure as haiku but focused on human nature, irony, and humor rather than nature.',
    history: 'Named after Karai Senryū (1718–1790), a judge of maekuzuke (verse-capping) contests in Edo. Distinguished from haiku by subject matter: human foibles rather than nature.',
    ethos: 'Wry observation of human nature. Where haiku finds beauty in nature, senryū finds comedy and pathos in people.',
    tips: ['No kigo (seasonal word) required — focus on human situations', 'Humor, irony, or satire are welcome', 'The punchline often lands in the final line'],
    constraints: ['No kigo or kireji required (unlike haiku)'],
    notablePoets: ['Karai Senryū', 'Tsukamoto Kunio'],
    exampleTitle: null,
  },

  katauta: {
    name: 'Katauta',
    description: '5 — 7 — 7 · half-poem',
    pattern: [5, 7, 7],
    rhymeScheme: null,
    lineCount: 3,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'A "half-poem" of three lines, originally designed for call-and-response exchange.',
    history: 'One of the earliest Japanese forms, a katauta is literally a "half-poem" — one side of a poetic dialogue. Two katauta together form a sedoka.',
    ethos: 'Incompleteness as invitation. The form implies a missing partner, a question awaiting its answer.',
    tips: ['Think of it as one half of a conversation', 'The 5-7-7 variant emphasizes the trailing resolution', 'Can be paired with another katauta to form a sedoka'],
    constraints: ['Variant patterns: 5-7-5 or 5-7-7'],
    notablePoets: [],
    exampleTitle: null,
  },

  sedoka: {
    name: 'Sedōka',
    description: '5–7–7–5–7–7 · question & answer',
    pattern: [5, 7, 7, 5, 7, 7],
    rhymeScheme: null,
    lineCount: 6,
    stanzas: [3, 3],
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'Two joined katauta forming a question-and-answer poem in six lines.',
    history: 'An ancient Japanese form composed of two katauta. Found in the Man\'yōshū, often used for dialogues or exchanges between lovers.',
    ethos: 'Dialogue and duality. Each half-poem speaks to the other across a structural divide.',
    tips: ['First stanza poses a question or image; second stanza responds', 'The two halves should feel like distinct voices or perspectives', 'The pivot between stanzas is where the poem turns'],
    constraints: ['Two katauta (5-7-7 + 5-7-7) joined as question and answer'],
    notablePoets: [],
    exampleTitle: null,
  },

  choka: {
    name: 'Chōka',
    description: '5–7 alternating · ends 5–7–7',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'partial',
    summary: 'Long Japanese poem alternating 5- and 7-syllable lines, closing with a 5-7-7 cadence.',
    history: 'The longest traditional Japanese form, used for court ceremonies and public occasions in the Nara period (710–794). Kakinomoto no Hitomaro was its greatest practitioner. Often followed by one or more hanka (envoi tanka).',
    ethos: 'Expansive and ceremonial. Where haiku compresses, chōka unfolds — building through accumulation toward a resonant close.',
    tips: ['Alternate 5-7 syllable lines freely', 'End with 5-7-7 to create a tanka-like cadence', 'Consider adding a hanka (envoi tanka) after the main poem'],
    constraints: ['Alternating 5-7 pattern', 'Must end with 5-7-7', 'Variable length — no fixed line count'],
    notablePoets: ['Kakinomoto no Hitomaro', 'Yamanoue no Okura'],
    exampleTitle: null,
  },

  dodoitsu: {
    name: 'Dodoitsu',
    description: '7–7–7–5 · folk song',
    pattern: [7, 7, 7, 5],
    rhymeScheme: null,
    lineCount: 4,
    stanzas: null,
    category: 'east-asian',
    origin: 'Japan',
    validationLevel: 'full',
    summary: 'Four-line unrhymed Japanese folk song form, typically about love or humor.',
    history: 'Emerged during the Edo period (1603–1868) as a popular song form, often performed by geisha. The 7-7-7-5 pattern (26 syllables) gives it a lilting, musical quality distinct from the more literary tanka.',
    ethos: 'Earthy, musical, and intimate. A form for the voice rather than the page — love, longing, and wit.',
    tips: ['The shorter final line creates natural emphasis — save your strongest image for it', 'Themes of love and humor are traditional', 'Think of it as a song lyric more than a literary poem'],
    constraints: [],
    notablePoets: [],
    exampleTitle: null,
  },

  sijo: {
    name: 'Sijo',
    description: '3 lines · 14–16 syl each · twist in line 3',
    pattern: [15, 15, 15],
    rhymeScheme: null,
    lineCount: 3,
    stanzas: null,
    category: 'east-asian',
    origin: 'Korea',
    validationLevel: 'full',
    summary: 'Korean three-line form with a thematic twist or surprise in the final line.',
    history: 'Originated in the Goryeo period (918–1392) and flourished during the Joseon Dynasty. The name means "current tune" or "song of the times." Both aristocrats and commoners wrote sijo, making it one of Korea\'s most democratic literary forms.',
    ethos: 'Statement, development, twist. Line 1 introduces, line 2 develops, line 3 subverts or resolves with a surprising turn.',
    tips: ['Each line has 14-16 syllables, often divided into hemistichs', 'Line 3 must contain a twist, counter-theme, or unexpected resolution', 'The twist often begins with a surprising image or sound in the first few syllables of line 3'],
    constraints: ['14-16 syllables per line (flexible)', 'Line 3 must contain thematic twist'],
    notablePoets: ['Yun Seondo', 'Hwang Jini', 'Kim Sowol'],
    exampleTitle: null,
  },

  lucBat: {
    name: 'Lục Bát',
    description: '6–8 alternating · interlocking rhyme',
    pattern: null,
    rhymeScheme: null,
    lineCount: null,
    stanzas: null,
    category: 'east-asian',
    origin: 'Vietnam',
    validationLevel: 'partial',
    summary: 'Vietnamese national verse form with alternating 6- and 8-syllable lines linked by interlocking rhyme.',
    history: 'The foundational verse form of Vietnamese literature, used in the national epic Truyện Kiều (The Tale of Kiều) by Nguyễn Du (1820). Predates written Vietnamese literature, originating in oral folk poetry.',
    ethos: 'Flowing, musical, and endlessly extensible. The interlocking rhyme creates a chain that can run for thousands of lines.',
    tips: ['6-syllable line rhymes with the 6th syllable of the following 8-syllable line', 'The 8th syllable of the 8-syllable line rhymes with the 6th syllable of the next 6-syllable line', 'In Vietnamese, tonal rules (bằng/trắc) govern which tones can appear at rhyme positions'],
    constraints: ['Alternating 6-8 syllable lines', 'Interlocking rhyme chain between lines', 'Traditional: Vietnamese tonal rules at rhyme positions'],
    notablePoets: ['Nguyễn Du', 'Hồ Xuân Hương'],
    exampleTitle: 'Truyện Kiều (The Tale of Kiều)',
  },

  pantun: {
    name: 'Pantun',
    description: 'ABAB · shadow + meaning',
    pattern: null,
    rhymeScheme: ['A', 'B', 'A', 'B'],
    lineCount: 4,
    stanzas: null,
    category: 'east-asian',
    origin: 'Malay Archipelago',
    validationLevel: 'full',
    summary: 'Malay quatrain where the first two "shadow" lines create an oblique metaphorical link to the meaning in lines 3-4.',
    history: 'One of the oldest Malay literary forms, dating back centuries in oral tradition. Recognized by UNESCO as Intangible Cultural Heritage. Spread throughout Southeast Asia and influenced the French pantoum.',
    ethos: 'Indirection as art. The pembayang (shadow lines 1-2) never state the theme directly — they create a mood, sound, or image that resonates with the maksud (meaning lines 3-4).',
    tips: ['Lines 1-2 (pembayang/shadow) should create imagery that obliquely mirrors lines 3-4 (maksud/meaning)', 'The connection between shadow and meaning can be sonic, visual, or emotional — not necessarily logical', 'ABAB rhyme links the two halves together'],
    constraints: ['Lines 1-2: pembayang (foreshadowing imagery)', 'Lines 3-4: maksud (actual meaning)', 'Connection between halves is oblique, not direct'],
    notablePoets: [],
    exampleTitle: null,
  },

  tanaga: {
    name: 'Tanaga',
    description: '7–7–7–7 · AABB',
    pattern: [7, 7, 7, 7],
    rhymeScheme: ['A', 'A', 'B', 'B'],
    lineCount: 4,
    stanzas: null,
    category: 'east-asian',
    origin: 'Philippines',
    validationLevel: 'full',
    summary: 'Pre-colonial Filipino quatrain of four 7-syllable lines, often encoding riddles or proverbs.',
    history: 'An indigenous Filipino form predating Spanish colonization (pre-1565). Tanaga were inscribed on bamboo and transmitted orally, often containing riddle-like wisdom, proverbs, and courtship verses.',
    ethos: 'Compact wisdom. Each tanaga is a self-contained jewel of meaning — a riddle, a proverb, or a declaration compressed into 28 syllables.',
    tips: ['Rhyme scheme can be AABB or ABAB — both are traditional', 'Riddle-like or proverbial content is characteristic', 'Every syllable counts — aim for maximum density of meaning'],
    constraints: ['Rhyme scheme: AABB or ABAB (both traditional)'],
    notablePoets: [],
    exampleTitle: null,
  },

  americanCinquain: {
    name: 'American Cinquain',
    description: '2–4–6–8–2',
    pattern: [2, 4, 6, 8, 2],
    rhymeScheme: null,
    lineCount: 5,
    stanzas: null,
    category: 'east-asian',
    origin: 'United States',
    validationLevel: 'full',
    summary: 'Five-line form with a 2-4-6-8-2 syllable pattern, swelling to fullness before snapping shut.',
    history: 'Invented by Adelaide Crapsey (1878–1914), inspired by Japanese forms. Published posthumously in her collection Verse (1915). The form captures a moment of perception in a breath-like arc.',
    ethos: 'Expansion and sudden closure. The syllable count swells outward then collapses — like a wave breaking, or a breath released.',
    tips: ['The final 2-syllable line carries enormous weight — choose those words carefully', 'The 8-syllable line is your fullest moment; the 2-syllable ending should reframe it', 'Imagery of stillness punctuated by action works well with this shape'],
    constraints: [],
    notablePoets: ['Adelaide Crapsey'],
    exampleTitle: 'November Night (Crapsey)',
  },

  // ── European & Western ────────────────────────────────────────────────────

  // ── Middle Eastern & Islamic ──────────────────────────────────────────────

  // ── African Traditions ────────────────────────────────────────────────────

  // ── Celtic & British Isles ────────────────────────────────────────────────

  // ── Modern & Invented ─────────────────────────────────────────────────────

  // ── Open Forms ────────────────────────────────────────────────────────────

};
